### ISSUE TITLE
Imagem é pega duas vezes na classe ScaleImage

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.facetada#1]
No método render da classe ScaleImage, a imagem é pega duas vezes sem necessidade:

https://github.com/plonegovbr/brasil.gov.facetada/blob/6b0adc8a9c71864a25667d2b7c017e61ebb69e9d/src/brasil/gov/facetada/browser/scaleimage/scaleimage.py#L102-L103

**Comment by claytonc** [comment]
@idgserpro 
Foi efetuada a correção https://github.com/plonegovbr/brasil.gov.facetada/pull/13
