### ISSUE TITLE
Import  IBrowserLayer error

### ISSUE THREAD

**Issue by makelli** [plonegovbr/brasil.gov.facetada#8]
WARNING OFS.Uninstalled Could not import class 'IBrowserLayer' from module 'brasil.gov.facetada.interfaces'

**Comment by hvelarde** [comment]
mais detalhes, favor: você tinha instalado `brasil.gov.facetada`, desinstalou e removeu o egg e acontece esse erro?

esse teste aqui demostra que isso não deveria acontecer:

https://github.com/plonegovbr/brasil.gov.facetada/blob/master/src/brasil/gov/facetada/tests/test_setup.py#L102-L103

**Comment by idgserpro** [comment]
Essa issue será discutida em https://github.com/plonegovbr/brasil.gov.portal/issues/363 pois não parece ser um erro do pacote e sim de configuração.
